_BASE_: LOMM_Online_R50.yaml

MODEL:
  META_ARCHITECTURE: "LOMM_offline"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 15
  SAMPLING_FRAME_RANGE: 7
  REVERSE_AGU: True